# Databricks dbt Profile
# 
# This profile configures dbt to connect to Databricks
# Uses environment variables for sensitive data
#
# When running on a Databricks cluster (notebook/job), set method to 'session'
# When running locally or from CI/CD, set method to 'http'

databricks:
  # Development target (default)
  target: dev
  
  outputs:
    # Dev target for running from Databricks notebooks/jobs
    dev:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'iot_streaming_dev') }}"
      schema: "silver_dev"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      # Use 'session' method when running on a Databricks cluster
      # This uses the current SparkSession directly
      method: "{{ env_var('DBT_METHOD', 'session') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH', '/sql/1.0/warehouses/starter') }}"
      token: "{{ env_var('DATABRICKS_TOKEN', '') }}"
      threads: 4
      connect_retries: 3
      connect_timeout: 60
    
    # Local development target (uses HTTP connection)
    dev_local:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'iot_streaming_dev') }}"
      schema: "silver_dev"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      method: http
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH', '/sql/1.0/warehouses/starter') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
      connect_retries: 3
      connect_timeout: 60
    
    staging:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'iot_streaming_staging') }}"
      schema: "silver_staging"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      method: "{{ env_var('DBT_METHOD', 'session') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH', '/sql/1.0/warehouses/starter') }}"
      token: "{{ env_var('DATABRICKS_TOKEN', '') }}"
      threads: 4
      connect_retries: 3
      connect_timeout: 60
    
    prod:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'iot_streaming_prod') }}"
      schema: "silver_prod"
      host: "{{ env_var('DATABRICKS_HOST') }}"
      method: "{{ env_var('DBT_METHOD', 'session') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH', '/sql/1.0/warehouses/starter') }}"
      token: "{{ env_var('DATABRICKS_TOKEN', '') }}"
      threads: 8
      connect_retries: 5
      connect_timeout: 120
