iot_simulator_datalake:
  target: dev
  outputs:
    dev:
      type: databricks
      method: http
      schema: 'bronze'
      host: 'dbc-6ee8b0d3-4446.cloud.databricks.com'
      http_path: '/sql/1.0/warehouses/1e9ad081dfddd470'
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"